### ISSUE TITLE
Fix print_best_algorithm_code function to work with all segmentors

### ISSUE THREAD

**Issue by colbrydi** [colbrydi/see-segment#6] opened 2020-06-12 19:22 UTC
While giving a demo, I noticed that some of the segmentors do not work when we run the "print_best_algorithm_code".  I do not have an exmaple. We should unit test all of the segmentors and find/fix the ones that do not work.

**Comment by kai-pinckard** [comment] 2020-07-08 23:25
Running the following code can reproduce the error.

from see import GeneticSearch, Segmentors

params =  ["CT", 4301, 0.237, 9512, 0.21, 5951, 5937, 10, 0.77, 2971, 3685, 3, 1, 100, 0.97, [1, 1], 0.0, "checkerboard", "checkerboard", 3, 493, -28, 0.0, 0.0, 0.0]
code = GeneticSearch.print_best_algorithm_code(params)

**Comment by kai-pinckard** [comment] 2020-07-09 01:07
This issue has been resolved.
It turns out that the error occurs because the code relies on the assumption that the first ']' in the file will always be the closing bracket immediately following the first occurrence of "self.params". This was fixed by searching for the first ']' that occurs after the first occurrence of "self.params".

**Closed** 2020-07-31 18:15 UTC
Labels: bug
